// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.web,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaYjptMCa9dMWbRog5mn5C-8qgTLwAev0',
    appId: '1:1047896995916:web:824042a757ff5ef06fdce9',
    messagingSenderId: '1047896995916',
    projectId: 'animal-onomatope',
    authDomain: 'animal-onomatope.firebaseapp.com',
    storageBucket: 'animal-onomatope.appspot.com',
    measurementId: 'G-T4YXX4GR4B',
  );
}
